project:
  type: book

book:
  title: "Data analysis"
  author: "Francesco Visconti"
  date: "3/20/2023"
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - tools.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

